### ISSUE TITLE
Blob test

### ISSUE THREAD

**Issue by ddkwork** [ploxxxy/node-tdf#2]
Hi, why https://github.com/ploxxxy/tdf.js/blob/main/tests%2Fblob.test.ts#L6-L6

Is not []byte{0xda, 0x1b, 0x35, 0x2, 0x4, 0xde, 0xad, 0xbe, 0xef}

**Comment by ploxxxy** [comment]
Hi, turns out writing blobs was broken. It now should work as intended, thanks

**Comment by ddkwork** [comment]
> Hi, turns out writing blobs was broken. It now should work as intended, thanks

Nice work, i will try to translate it as go

https://github.com/ddkwork/tdf
